import { describe, it, expect, vi, beforeEach } from 'vitest';
import * as actions from './personalActions';
const records = new Map<string, Record<string, unknown>>();
const ref = (path: string) => ({ path, id: path.split('/').at(-1), get: async () => snap(path), collection: (name: string) => collection(`${path}/${name}`) });
const snap = (path: string) => ({ exists: records.has(path), id: path.split('/').at(-1), ref: ref(path), data: () => records.get(path) });
const collection = (path: string) => ({ doc: (id: string) => ref(`${path}/${id}`), where: () => ({ where: () => ({ limit: () => ({ get: async () => ({ docs: [] }) }) }) }) });
vi.mock('../firestoreRest', () => ({ getAdminDb: () => ({ collection, runTransaction: async (fn: (transaction: { get: (r: {path:string}) => Promise<ReturnType<typeof snap>>; set: (r: {path:string}, v: Record<string,unknown>) => unknown; delete: (r: {path:string}) => unknown }) => Promise<unknown>) => fn({ get: async (r: {path:string}) => snap(r.path), set: (r: {path:string}, v: Record<string,unknown>) => records.set(r.path, v), delete: (r: {path:string}) => records.delete(r.path) }) }) }));
async function api() { return actions; }
beforeEach(() => { records.clear(); records.set('messages/m1', { hidden: false, expiresAt: Date.now()+100000 }); });
describe('server owned chat actions', () => {
 it('keeps one reaction per account and message and toggles it off', async () => { const m = await api(); await m.toggleMessageReaction('alice', { messageId: 'm1', emoji: '👍', userId: 'victim' }); await m.toggleMessageReaction('alice', { messageId: 'm1', emoji: '🔥' }); const reactions = [...records.entries()].filter(([k])=>k.startsWith('message_reactions/')); expect(reactions).toHaveLength(1); expect(reactions[0][1]).toMatchObject({ userId: 'alice', emoji: '🔥' }); await m.toggleMessageReaction('alice', { messageId: 'm1', emoji: '🔥' }); expect([...records.keys()].filter(k=>k.startsWith('message_reactions/'))).toHaveLength(0); });
 it('rejects hidden, expired, missing messages and unsupported emojis', async () => { const m = await api(); for (const data of [{ hidden:true }, { expiresAt:1 }]) { records.set('messages/m1', data); await expect(m.toggleMessageReaction('alice',{messageId:'m1',emoji:'👍'})).rejects.toThrow(); } await expect(m.toggleMessageReaction('alice',{messageId:'missing',emoji:'👍'})).rejects.toThrow(); await expect(m.toggleMessageReaction('alice',{messageId:'m1',emoji:'x'})).rejects.toThrow(); });
 it('rejects external URLs and another users private image', async () => { const m = await api(); for (const url of ['https://evil.example/a.png','https://wfmokinfcypfpdisussw.supabase.co/storage/v1/object/public/chat-images/chat/victim/product/2026-10/a.png']) await expect(m.savePersonalImage('alice',{url})).rejects.toThrow(); });
 it('deduplicates owned images and derives the owner on the server', async () => { const m = await api(); const input = { url:'https://wfmokinfcypfpdisussw.supabase.co/storage/v1/object/public/chat-images/chat/alice/product/2026-10/a.png', originalOwnerUid:'victim', createdAt:1 }; await m.savePersonalImage('alice',input); await m.savePersonalImage('alice',input); const saved = [...records.entries()].filter(([k])=>k.startsWith('users/alice/images/')); expect(saved).toHaveLength(1); expect(saved[0][1].originalOwnerUid).toBe('alice'); expect(saved[0][1].createdAt).toBeGreaterThan(1); });
 it('allows reuse only when a server library record matches the URL', async () => { const m = await api(); const sha='a'.repeat(64), url='https://wfmokinfcypfpdisussw.supabase.co/storage/v1/object/public/chat-images/chat/victim/shared/2026-10/a.png'; await expect(m.savePersonalImage('alice',{url,sha256:sha})).rejects.toThrow(); records.set(`chat_image_library/${sha}`,{url,ownerUid:'victim',sha256:sha}); await m.savePersonalImage('alice',{url,sha256:sha}); expect([...records.values()].some(v=>v.originalOwnerUid==='victim' && v.shared===true)).toBe(true); });
});
