import type { PublicStoreSummary } from "./publicMarketplace";
import type { StoreSchedule } from "./schedule";

export type DemoMarketplaceCategory =
  | "food"
  | "drinks"
  | "desserts"
  | "crafts"
  | "stationery";

export interface DemoMarketplaceStore extends PublicStoreSummary {
  demoCategory: DemoMarketplaceCategory;
  demoRating: number;
  demoReviewCount: number;
  demoTags: string[];
}

const CLOSED_SCHEDULE: StoreSchedule = {
  monday: { slots: [] },
  tuesday: { slots: [] },
  wednesday: { slots: [] },
  thursday: { slots: [] },
  friday: { slots: [] },
  saturday: { slots: [] },
  sunday: { slots: [] },
};

export const DEMO_MARKETPLACE_STORES: DemoMarketplaceStore[] = [
  {
    id: "demo-postres-ana",
    name: "Postres de Ana",
    slug: "demo-postres-ana",
    description: "Postres caseros que alegran el día",
    deliveryLocation: "Campus Central",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1694067508035-6cccccb95cb0?auto=format&fit=crop&w=1000&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: true,
    openNow: true,
    marketplaceLabel: "POSTRES",
    marketplaceNote: "LA VIDA ES MÁS DULCE EN EL TEC :)",
    marketplaceTags: ["Postres", "Dulces"],
    marketplaceVariant: "cloud-1",
    demoCategory: "desserts",
    demoRating: 4.9,
    demoReviewCount: 120,
    demoTags: ["Postres", "Dulces"],
  },
  {
    id: "demo-snack-lab",
    name: "Snack Lab",
    slug: "demo-snack-lab",
    description: "Snacks creativos para mentes brillantes",
    deliveryLocation: "Campus Central",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=1000&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: true,
    openNow: true,
    marketplaceLabel: "SNACK LAB",
    marketplaceNote: "IDEAS QUE TAMBIÉN SE ANTOJAN :)",
    marketplaceTags: ["Comida", "Snacks"],
    marketplaceVariant: "cloud-2",
    demoCategory: "food",
    demoRating: 4.8,
    demoReviewCount: 98,
    demoTags: ["Comida", "Snacks"],
  },
  {
    id: "demo-tortas-punto",
    name: "Tortas El Punto",
    slug: "demo-tortas-punto",
    description: "Tortas bien servidas para seguir la jornada",
    deliveryLocation: "Campus Central",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1639667852215-6d7d4fa1babb?auto=format&fit=crop&w=1000&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: true,
    openNow: true,
    marketplaceLabel: "TORTAS EL PUNTO",
    marketplaceNote: "BUENAS TORTAS, MEJORES PLÁTICAS",
    marketplaceTags: ["Comida", "Tortas"],
    marketplaceVariant: "cloud-3",
    demoCategory: "food",
    demoRating: 4.7,
    demoReviewCount: 150,
    demoTags: ["Comida", "Tortas"],
  },
  {
    id: "demo-cafe-campus",
    name: "Café del Campus",
    slug: "demo-cafe-campus",
    description: "Buen café para grandes ideas",
    deliveryLocation: "Campus Norte",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: true,
    openNow: true,
    marketplaceLabel: "Café del Campus",
    marketplaceNote: "CAFÉ · IDEAS · AMIGOS · PLANES",
    marketplaceTags: ["Bebidas", "Café"],
    marketplaceVariant: "cloud-4",
    demoCategory: "drinks",
    demoRating: 4.8,
    demoReviewCount: 110,
    demoTags: ["Bebidas", "Café"],
  },
  {
    id: "demo-artesanias-morelia",
    name: "Artesanías Morelia",
    slug: "demo-artesanias-morelia",
    description: "Accesorios únicos, hechos con el corazón",
    deliveryLocation: "Campus Norte",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1000&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: true,
    openNow: true,
    marketplaceLabel: "Artesanías Morelia",
    marketplaceNote: "ARTE QUE CONECTA ♡",
    marketplaceTags: ["Artesanías", "Accesorios"],
    marketplaceVariant: "cloud-5",
    demoCategory: "crafts",
    demoRating: 4.9,
    demoReviewCount: 76,
    demoTags: ["Artesanías", "Accesorios"],
  },
  {
    id: "demo-papeleria-express",
    name: "Papelería Express",
    slug: "demo-papeleria-express",
    description: "Todo lo que necesitas para dar lo mejor de ti",
    deliveryLocation: "Campus Central",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1717079557046-f144cd4dd946?auto=format&fit=crop&w=1000&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: true,
    openNow: true,
    marketplaceLabel: "PAPELERÍA EXPRESS",
    marketplaceNote: "TUS IDEAS TAMBIÉN NECESITAN BUENAS HERRAMIENTAS :)",
    marketplaceTags: ["Papelería", "Útiles"],
    marketplaceVariant: "cloud-6",
    demoCategory: "stationery",
    demoRating: 4.9,
    demoReviewCount: 134,
    demoTags: ["Papelería", "Útiles"],
  },
];
