import type { PublicStoreSummary } from "./publicMarketplace";
import type { StoreSchedule } from "./schedule";

const CLOSED_SCHEDULE: StoreSchedule = {
  monday: { slots: [] },
  tuesday: { slots: [] },
  wednesday: { slots: [] },
  thursday: { slots: [] },
  friday: { slots: [] },
  saturday: { slots: [] },
  sunday: { slots: [] },
};

export const DEMO_MARKETPLACE_HERO =
  "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1800&q=88";

export const DEMO_STORES: PublicStoreSummary[] = [
  {
    id: "demo-postres-ana",
    name: "Postres de Ana",
    slug: "demo-postres-ana",
    description: "Postres caseros que alegran el día: brownies, cupcakes y cheesecakes.",
    deliveryLocation: "Patio central",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: true,
    openNow: true,
  },
  {
    id: "demo-snack-lab",
    name: "Snack Lab",
    slug: "demo-snack-lab",
    description: "Snacks creativos, botanas y antojos para el break entre clases.",
    deliveryLocation: "Explanada",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=1200&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: true,
    openNow: true,
  },
  {
    id: "demo-tortas-punto",
    name: "Tortas El Punto",
    slug: "demo-tortas-punto",
    description: "Tortas bien servidas, combinaciones clásicas y sabor de campus.",
    deliveryLocation: "Edificio A",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: false,
    openNow: false,
  },
  {
    id: "demo-cafe-campus",
    name: "Café del Campus",
    slug: "demo-cafe-campus",
    description: "Café, ideas, amigos y algo frío para seguir con el día.",
    deliveryLocation: "Biblioteca",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: true,
    openNow: true,
  },
  {
    id: "demo-artesanias",
    name: "Artesanías Morelia",
    slug: "demo-artesanias",
    description: "Piezas hechas a mano, accesorios únicos y detalles con identidad.",
    deliveryLocation: "Edificio B",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: true,
    openNow: true,
  },
  {
    id: "demo-papeleria",
    name: "Papelería Express",
    slug: "demo-papeleria",
    description: "Libretas, plumones, útiles y materiales para proyectos y clases.",
    deliveryLocation: "Edificio C",
    logoUrl: null,
    coverUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=88",
    schedule: CLOSED_SCHEDULE,
    operationalMode: "manual",
    manualOpen: true,
    openNow: true,
  },
];
